# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-22 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Config 1', max_length=255, unique=True)),
                ('on_test', models.BooleanField(default=True)),
                ('search_on', models.BooleanField(default=True)),
                ('breaking_news_on', models.BooleanField(default=True)),
                ('headline_on', models.BooleanField(default=True)),
                ('slider_on', models.BooleanField(default=True)),
                ('photo_news_on', models.BooleanField(default=True)),
                ('social_tab_on', models.BooleanField(default=True)),
                ('latest_news_tabs_on', models.BooleanField(default=True)),
                ('most_readable_news_tabs_on', models.BooleanField(default=True)),
                ('todays_speech_tab_on', models.BooleanField(default=True)),
                ('weather_on', models.BooleanField(default=True)),
                ('live_score_board_tab_on', models.BooleanField(default=True)),
                ('adspace1_on', models.BooleanField(default=True)),
                ('adspace2_on', models.BooleanField(default=True)),
                ('adspace3_on', models.BooleanField(default=True)),
                ('adspace4_on', models.BooleanField(default=True)),
                ('adspace5_on', models.BooleanField(default=True)),
                ('adspace6_on', models.BooleanField(default=True)),
                ('adspace7_on', models.BooleanField(default=True)),
                ('adspace8_on', models.BooleanField(default=True)),
                ('adspace9_on', models.BooleanField(default=True)),
                ('adspace10_on', models.BooleanField(default=True)),
                ('adspace11_on', models.BooleanField(default=True)),
                ('adspace12_on', models.BooleanField(default=True)),
                ('adspace13_on', models.BooleanField(default=True)),
                ('adspace14_on', models.BooleanField(default=True)),
                ('adspace15_on', models.BooleanField(default=True)),
                ('adspace16_on', models.BooleanField(default=True)),
                ('adspace17_on', models.BooleanField(default=True)),
                ('adspace18_on', models.BooleanField(default=True)),
                ('cache_on', models.BooleanField(default=True)),
                ('news_type_3_link_limit', models.IntegerField(default=5)),
                ('news_type_4_link_limit', models.IntegerField(default=5)),
                ('headline_limit', models.IntegerField(default=5)),
                ('breaking_news_limit', models.IntegerField(default=3)),
                ('latest_news_limit', models.IntegerField(default=10)),
                ('most_readable_news_limit', models.IntegerField(default=10)),
                ('default_words_count', models.IntegerField(default=38)),
                ('latest_news_words_count', models.IntegerField(default=38)),
                ('popular_news_words_count', models.IntegerField(default=40)),
                ('most_readable_news_word_count', models.IntegerField(default=40)),
                ('position_123_words_count', models.IntegerField(default=38)),
                ('position_456_words_count', models.IntegerField(default=38)),
                ('category_news_words_count', models.IntegerField(default=38)),
                ('cache_timeout_hour', models.IntegerField(default=1)),
                ('upload_image_width', models.IntegerField(default=600)),
                ('upload_image_height', models.IntegerField(default=250)),
                ('sorry_nothing_found_text', models.CharField(default='\u09a6\u09c1\u0983\u0996\u09bf\u09a4, \u0995\u09cb\u09a8 \u09ab\u09b2\u09be\u09ab\u09b2 \u09aa\u09be\u0993\u09df\u09be \u09af\u09be\u09df\u09a8\u09bf', max_length=255)),
                ('chief_editor_name', models.CharField(default='\u0986\u09b2\u09c0 \u09b9\u09be\u09b8\u09be\u09a8', max_length=255, verbose_name='\u09aa\u09cd\u09b0\u09a7\u09be\u09a8 \u09b8\u09ae\u09cd\u09aa\u09be\u09a6\u0995')),
                ('ceo_name', models.CharField(default='\u098f\u09b8.\u098f\u09ae.\u09b6\u09be\u09ae\u09c0\u09ae \u09b8\u09c1\u09b2\u09a4\u09be\u09a8', max_length=255, verbose_name='\u09aa\u09cd\u09b0\u09a7\u09be\u09a8 \u09a8\u09bf\u09b0\u09cd\u09ac\u09be\u09b9\u09c0 \u0995\u09b0\u09cd\u09ae\u0995\u09b0\u09cd\u09a4\u09be')),
                ('me_name', models.CharField(default='\u09ab\u099c\u09b2\u09c7 \u09b0\u09be\u09ac\u09cd\u09ac\u09c0', max_length=255, verbose_name='\u09ac\u09cd\u09af\u09ac\u09b8\u09cd\u09a5\u09be\u09aa\u09a8\u09be \u09b8\u09ae\u09cd\u09aa\u09be\u09a6\u0995')),
                ('bureau_chief_name', models.CharField(default='\u0986\u09b2 \u09ae\u09be\u09b8\u09c1\u09ae', max_length=255, verbose_name='\u09ac\u09cd\u09af\u09ac\u09b8\u09cd\u09a5\u09be\u09aa\u09a8\u09be \u09b8\u09ae\u09cd\u09aa\u09be\u09a6\u0995')),
                ('office_address', models.CharField(default='\u09b8\u09cd\u09af\u09c1\u099f- \u09eb/\u0987, \u098f \u098f\u0987\u099a \u099f\u09be\u0993\u09df\u09be\u09b0 (\u09eb\u09ae \u09a4\u09b2\u09be), \u09b0\u09cb\u09a1-\u09e8, \u09b8\u09c7\u0995\u09cd\u099f\u09b0-\u09e9, \u0989\u09a4\u09cd\u09a4\u09b0\u09be, \u09a2\u09be\u0995\u09be-\u09e7\u09e8\u09e9\u09e6', max_length=255, verbose_name='\u09ac\u09be\u09b0\u09cd\u09a4\u09be \u0993 \u09ac\u09be\u09a3\u09bf\u099c\u09cd\u09af\u09bf\u0995 \u0995\u09be\u09b0\u09cd\u09af\u09be\u09b2\u09df\u0983')),
                ('phones', models.CharField(default='+\u09ee\u09ee \u09e6\u09e7\u09ec\u09ed\u09ef-\u09ee\u09ee\u09ec-\u09ec\u09ec\u09ee', max_length=255, verbose_name='\u09ab\u09cb\u09a8')),
                ('email', models.CharField(default='admin@bdtouchnews.tk, news@bdtouchnews.tk', max_length=255, verbose_name='\u0987-\u09ae\u09c7\u0987\u09b2')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'News Configuration',
                'verbose_name_plural': 'News Configuration',
            },
        ),
    ]
