# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-16 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('bangla_name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('T1', 'Type 1'), ('T2', 'Type 2'), ('T3', 'Type 3'), ('T4', 'Type 4'), ('NO', 'None')], default='NO', max_length=2)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Category',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=255, unique=True)),
                ('image_file', models.ImageField(blank=True, max_length=255, upload_to='images/news/')),
                ('content', models.TextField()),
                ('reporter', models.CharField(blank=True, default='Online', max_length=255)),
                ('hits', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ManyToManyField(to='news.Category')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
            },
        ),
    ]
