# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-10 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateField(verbose_name='Date')),
                ('fajar', models.CharField(max_length=255, verbose_name='Fajar Time')),
                ('zohar', models.CharField(max_length=255, verbose_name='Zohar Time')),
                ('asar', models.CharField(max_length=255, verbose_name='Asar Time')),
                ('magrib', models.CharField(max_length=255, verbose_name='Magrib Time')),
                ('esha', models.CharField(max_length=255, verbose_name='Esha Time')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Prayer Time',
                'verbose_name_plural': 'Prayer Time',
            },
        ),
    ]
