# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-10 07:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adspace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('subscription_fees', models.DecimalField(decimal_places=4, max_digits=15)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Adspace',
                'verbose_name_plural': 'Adspace',
            },
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(auto_now=True)),
                ('image_file', models.ImageField(upload_to=b'')),
                ('image_click_url', models.CharField(max_length=255)),
                ('notes', models.TextField()),
                ('status', models.CharField(choices=[('1', 'active'), ('0', 'inactive')], default='0', max_length=2)),
                ('adspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='advertisement.Adspace')),
            ],
            options={
                'verbose_name': 'Ads',
                'verbose_name_plural': 'Ads',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=255)),
                ('phone1', models.CharField(blank=True, max_length=255)),
                ('phone2', models.CharField(blank=True, max_length=255)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('website', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Company',
            },
        ),
        migrations.AddField(
            model_name='advertisement',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='advertisement.Company'),
        ),
    ]
