# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-09 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(auto_now=True)),
                ('image_file', models.ImageField(max_length=255, upload_to=b'')),
                ('caption', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Slider Picture',
                'verbose_name_plural': 'Slider Pictures',
            },
        ),
    ]
