# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-10 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Horoscope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateField(verbose_name='Date')),
                ('mesh', models.TextField(verbose_name='\u09ae\u09c7\u09b7')),
                ('brisho', models.TextField(verbose_name='\u09ac\u09c3\u09b7')),
                ('mithun', models.TextField(verbose_name=' \u09ae\u09bf\u09a5\u09c1\u09a8')),
                ('korkot', models.TextField(verbose_name='\u0995\u09b0\u09cd\u0995\u099f')),
                ('shingho', models.TextField(verbose_name='\u09b8\u09bf\u0982\u09b9')),
                ('konna', models.TextField(verbose_name='\u0995\u09a8\u09cd\u09af\u09be')),
                ('tula', models.TextField(verbose_name='\u09a4\u09c1\u09b2\u09be')),
                ('brishchik', models.TextField(verbose_name='\u09ac\u09c3\u09b6\u09cd\u099a\u09bf\u0995')),
                ('dhanu', models.TextField(verbose_name='\u09a7\u09a8\u09c1')),
                ('mokor', models.TextField(verbose_name='\u09ae\u0995\u09b0')),
                ('kumvo', models.TextField(verbose_name='\u0995\u09c1\u09ae\u09cd\u09ad')),
                ('meen', models.TextField(verbose_name='\u09ae\u09c0\u09a8')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Horoscope',
                'verbose_name_plural': 'Horoscope',
            },
        ),
    ]
